### PR TITLE
Added instructions tests for RVI and RVM

### LINKED ISSUE #9: Adding more instructions like scalar?
Hello @camel-cdr,

I recently came to use your benchmarks for RVV performance. It's very easy-to-use, really appreciate your work :)

I'd also like to add some tests for scalar instructions to evaluate their performance. Just wondering would I contribute them back upstream? Since this repository is called `rvv-bench`, dunno if you like to keep it specific to RVV.

Also I'd like to add a different but simple pattern like to make strong dependency.
```
add t0, t0, t0
```

Let me know your thoughts! Thanks.

Zen

### PR DESCRIPTION
**Pull request by furuame**
Close #9

Lots of codes can be shared across rvi, rvm, rvv-1.0, but let's keep them for now.

### CODE REVIEW

**Comment by camel-cdr** [comment]
Looks great, I'll merge it soon, and then slightly adjust the formatting to my preferences.

I think the `multiline` macro isn't used anywhere, so I'll also remove that. I think I wrote it to benchmark multiple instructions with the existing macros.

**Comment by camel-cdr** [comment]
Where there any reasons for splitting rvi and rvm?
I think I'd prefer having the scalar code for all extensions in one file, we could then more easily add the entirety of rv64gcb.
The compiler settings could be used to enable/disable the extensions.

**Comment by furuame** [comment]
> Looks great, I'll merge it soon, and then slightly adjust the formatting to my preferences.
> 
> I think the `multiline` macro isn't used anywhere, so I'll also remove that. I think I wrote it to benchmark multiple instructions with the existing macros.

Ok, will do!

> Where there any reasons for splitting rvi and rvm?
I think I'd prefer having the scalar code for all extensions in one file, we could then more easily add the entirety of rv64gcb.
The compiler settings could be used to enable/disable the extensions.

Sure, let's do it. I was just thinking a scenario that a RISC-V core may not always support all the standard extensions at a time. But they should be rare now 🙂

**Comment by furuame** [comment]
> Where there any reasons for splitting rvi and rvm? I think I'd prefer having the scalar code for all extensions in one file, we could then more easily add the entirety of rv64gcb. The compiler settings could be used to enable/disable the extensions.

I'm making it `rvim` for now. Let's continue to add more instructions of other extensions until being `rvgcb`!

**Comment by camel-cdr** [comment]
@furuame I refactored the code, and added rv64gb support.
I decided to remove the common config.h, because I think you would choose different values for benchmarking rvv and scalar instructions.

**Comment by furuame** [comment]
> @furuame I refactored the code, and added rv64gb support. I decided to remove the common config.h, because I think you would choose different values for benchmarking rvv and scalar instructions.

Sounds good to me.

> C908 results are now on the website: https://camel-cdr.github.io/rvv-bench-results/canmv_k230/index.html (scroll to bottom)

Nice work!!! I'd be more interested in C920's 🙃

**Pull request merged**
